
Distance: main.o Distance.o ctect.o
		gcc main.o ctect.o Distance.o -o test_Distance -lm
 
main.o: main.c
		gcc -c main.c
 
Distance.o: ../Functions/Distance.c
		gcc -c ../Functions/Distance.c
		
ctect.o: ctect.c
		gcc -c ctect.c
