
Test: main.o Objem.o Speed.o Square.o time.o Vess_i_massa.o Distance.o ctect.o
		gcc main.o ctect.o Objem.o Speed.o Square.o time.o Vess_i_massa.o Distance.o -o test -lm

main.o: main.c
		gcc -c main.c

Distance.o: ../Functions/Distance.c
		gcc -c ../Functions/Distance.c

Objem.o: ../Functions/Objem.c
		gcc -c ../Functions/Objem.c

Speed.o: ../Functions/Speed.c
		gcc -c ../Functions/Speed.c

Square.o: ../Functions/Square.c
		gcc -c ../Functions/Square.c

time.o: ../Functions/time.c
		gcc -c ../Functions/time.c

Vess_i_massa.o: ../Functions/Vess_i_massa.c
		gcc -c ../Functions/Vess_i_massa.c

ctect.o: ctect.c
		gcc -c ctect.c
