
Distance: main.o Distance.o ctect.o
		gcc main.o ctect.o Distance.o -o test_Distance -lm

Objem: main.o Objem.o ctest.o
		gcc main.o ctest.o Objem.o -o test_Objem -lm

Speed: main.o Speed.o ctest.o
		gcc main.o ctest.o Speed.o -o test_Speed -lm

Square: main.o Square.o ctest.o
		gcc main.o ctest.o Square.o -o test_Square -lm

time: main.o time.o ctest.o
		gcc main.o ctest.o time.o -o test_time -lm

Vess_i_massa: main.o Vess_i_massa.o ctest.o
		gcc main.o ctest.o Vess_i_massa.o -o test_Vess_i_massa -lm

main.o: main.c
		gcc -c main.c

Distance.o: ../Functions/Distance.c
		gcc -c ../Functions/Distance.c

Objem: ../Functions/Objem.c
		gcc -c ../Functions/Objem.c

Speed: ../Functions/Speed.c
		gcc -c ../Functions/Speed.c

Square: ../Functions/Square.c
		gcc -c ../Functions/Square.c

time: ../Functions/time.c
		gcc -c ../Functions/time.c

Vess_i_massa: ../Functions/Vess_i_massa.c
		gcc -c ../Functions/Vess_i_massa.c

ctect.o: ctect.c
		gcc -c ctect.c
