Konverter: Konverter.o Distance.o Objem.o Square.o Vess_i_massa.o Speed.o time.o
		gcc -o konverter Konverter.o Distance.o Objem.o Square.o Vess_i_massa.o Speed.o time.o -lm

Konverter.o: Konverter.c
		gcc -c Konverter.c
		
Distance.o: Distance.c
		gcc -c Distance.c
		
Objem.o: Objem.c
		gcc -c Objem.c

Square.o: Square.c
		gcc -c Square.c
		
Vess_i_massa.o: Vess_i_massa.c
		gcc -c Vess_i_massa.c
		
Speed.o: Speed.c
		gcc -c Speed.c

time.o: time.c
		gcc -c time.c
		
